In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../Income-Statement/earnings_master_1758128825174.csv')
df.head()

,act_symbol,date,period,sales,cost_of_goods,gross_profit,selling_administrative_depreciation_amortization_expenses,income_after_depreciation_and_amortization,non_operating_income,interest_expense,...,investment_gains,other_income,income_from_continuing_operations,extras_and_discontinued_operations,net_income,income_before_depreciation_and_amortization,depreciation_and_amortization,average_shares,diluted_eps_before_non_recurring_items,diluted_net_eps
0,A,2012-10-31,Year,6858000000,3254000000,3604000000,2485000000,1119000000,25000000,101000000,...,0,0,1153000000,0,1153000000,1.420000e+09,301000000.0,353000000,3.12,3.27
1,A,2013-10-31,Year,6782000000,3247000000,3535000000,2584000000,951000000,15000000,107000000,...,0,0,724000000,0,724000000,1.323000e+09,372000000.0,345000000,2.88,2.10
2,A,2014-10-31,Year,6981000000,3388000000,3593000000,2762000000,831000000,-72000000,113000000,...,0,0,504000000,0,504000000,1.193000e+09,362000000.0,338000000,3.04,1.49
3,A,2015-10-31,Year,4038000000,1997000000,2041000000,1519000000,522000000,24000000,66000000,...,0,0,438000000,-37000000,401000000,7.750000e+08,253000000.0,335000000,1.74,1.20
4,A,2016-07-31,Quarter,1044000000,502000000,542000000,396000000,146000000,5000000,17000000,...,0,0,124000000,0,124000000,NaN,NaN,328000000,0.49,0.38

In [ ]:
df.isnull()

,act_symbol,date,period,sales,cost_of_goods,gross_profit,selling_administrative_depreciation_amortization_expenses,income_after_depreciation_and_amortization,non_operating_income,interest_expense,...,investment_gains,other_income,income_from_continuing_operations,extras_and_discontinued_operations,net_income,income_before_depreciation_and_amortization,depreciation_and_amortization,average_shares,diluted_eps_before_non_recurring_items,diluted_net_eps
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,False